name: frontend
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.3.0
  provider: ^6.1.2
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.6
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0
  http: ^0.13.0 
  dotted_border: ^2.1.0
  camera: ^0.11.1
  socket_io_client: ^3.0.2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Massage_Image01.png
    - assets/images/Massage_Image03.png
    - assets/images/Massage_Image11.png
    - assets/images/profilePicture.jpg
